language: python

python:
  - "3.6"

before_install:
  - openssl aes-256-cbc -K $encrypted_4bedb345daab_key -iv $encrypted_4bedb345daab_iv
    -in travis_rsa.enc -out travis_rsa -d
  - chmod 600 travis_rsa
  - mv travis_rsa ~/.ssh/id_rsa

after_success:
  - bash ./deploy.sh